import { Platform, StyleSheet } from 'react-native';
import { spacing } from '../../theme';

/*
 * The workspace's look: a poster in the occasion's colours, floating cards on
 * a soft lilac page, gradients carrying the colour.
 */
export const WS_PAGE = '#f8f5fb';
const INK = '#1a1f3d';
const MUTED = '#6b6488';
const LINE = '#efeaf6';

const lift = Platform.select({
  ios: {
    shadowColor: '#3a2470',
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  android: { elevation: 3 },
});

export const screenUi = StyleSheet.create({
  page: { backgroundColor: WS_PAGE },
});

export const ringStyles = StyleSheet.create({
  box: { alignItems: 'center', justifyContent: 'center' },
  svg: { position: 'absolute', transform: [{ rotate: '-90deg' }] },
});

export const heroStyles = StyleSheet.create({
  poster: {
    paddingHorizontal: spacing.lg,
    paddingBottom: 64,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    overflow: 'hidden',
  },
  fill: { ...StyleSheet.absoluteFill },
  glow: { position: 'absolute', borderRadius: 999 },
  glowOne: { top: -90, right: -70, width: 260, height: 260, opacity: 0.35 },
  glowTwo: {
    bottom: -120,
    left: -80,
    width: 260,
    height: 260,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  art: { position: 'absolute', top: 0, right: -40, width: 300, height: 200, opacity: 0.22 },
  confetti: { position: 'absolute', top: 70, right: 0, width: 170, height: 150, opacity: 0.55 },

  topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  glassButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  topTitle: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  topSpacer: { width: 40 },
  refChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    maxWidth: 150,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  refText: { color: 'rgba(255,255,255,0.92)', fontSize: 11, fontWeight: '700', letterSpacing: 0.4 },

  eyebrowRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 22 },
  emoji: { fontSize: 26, lineHeight: 32 },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    flexShrink: 1,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  statusText: { color: INK, fontSize: 12, fontWeight: '700', flexShrink: 1 },
  title: {
    color: '#ffffff',
    fontSize: 36,
    lineHeight: 44,
    fontWeight: '800',
    letterSpacing: -0.8,
    marginTop: 10,
  },

  countRow: { flexDirection: 'row', alignItems: 'center', gap: 18, marginTop: 18 },
  countInner: { alignItems: 'center', justifyContent: 'center' },
  countNumber: { color: '#ffffff', fontSize: 34, lineHeight: 38, fontWeight: '800' },
  countLabel: { color: 'rgba(255,255,255,0.85)', fontSize: 11, fontWeight: '600', marginTop: -2 },
  countToday: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  dateBlock: {
    width: 84,
    height: 92,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  dateMonth: { color: 'rgba(255,255,255,0.85)', fontSize: 12, fontWeight: '700', letterSpacing: 1 },
  dateDay: { color: '#ffffff', fontSize: 34, lineHeight: 40, fontWeight: '800' },
  facts: { flex: 1, gap: 10 },
  fact: { flexDirection: 'row', alignItems: 'flex-start', gap: 9 },
  factIcon: {
    width: 26,
    height: 26,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  factText: { flex: 1, color: 'rgba(255,255,255,0.95)', fontSize: 13.5, lineHeight: 19, paddingTop: 3 },
  factStrong: { fontWeight: '700', color: '#ffffff' },

  organizerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 20,
    padding: 10,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.6)',
  },
  avatarText: { color: '#ffffff', fontSize: 14, fontWeight: '800' },
  organizerText: { flex: 1, minWidth: 0 },
  organizerLead: { color: 'rgba(255,255,255,0.75)', fontSize: 11 },
  organizerName: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  messageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: '#ffffff',
  },
  messageText: { fontSize: 13, fontWeight: '700' },

  statsCard: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: spacing.md,
    marginTop: -44,
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderRadius: 24,
    backgroundColor: '#ffffff',
    ...lift,
  },
  stat: { alignItems: 'center', gap: 6, flex: 1 },
  statValue: { color: INK, fontSize: 13, fontWeight: '800' },
  statLabel: { color: MUTED, fontSize: 12, fontWeight: '600' },

  tabs: { marginTop: 18 },
  tabsRow: { paddingHorizontal: spacing.md, gap: 8 },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    overflow: 'hidden',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: LINE,
  },
  tabActive: { borderColor: 'transparent' },
  tabLabel: { color: MUTED, fontSize: 14, fontWeight: '600' },
  tabLabelActive: { color: '#ffffff', fontWeight: '700' },
});

export const sectionUi = StyleSheet.create({
  section: { marginTop: 22, paddingHorizontal: spacing.md },
  head: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  headMark: {
    width: 30,
    height: 30,
    borderRadius: 10,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headTitle: { flex: 1, color: INK, fontSize: 18, fontWeight: '800', letterSpacing: -0.2 },
  headAside: {
    color: '#7c5cdb',
    fontSize: 12,
    fontWeight: '700',
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: 999,
    backgroundColor: '#f1ecff',
    overflow: 'hidden',
  },
  card: {
    borderRadius: 22,
    padding: spacing.md,
    backgroundColor: '#ffffff',
    ...lift,
  },

  empty: { alignItems: 'center', paddingVertical: 10, gap: 10 },
  emptyBlob: {
    width: 64,
    height: 64,
    borderRadius: 24,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: { color: MUTED, fontSize: 14, lineHeight: 20, textAlign: 'center', paddingHorizontal: 12 },

  step: { flexDirection: 'row', gap: 12 },
  stepRail: { alignItems: 'center', width: 26 },
  stepMark: {
    width: 26,
    height: 26,
    borderRadius: 13,
    overflow: 'visible',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepMarkTodo: { borderWidth: 2, borderColor: '#e2dcef', backgroundColor: '#ffffff' },
  stepLine: { width: 2, flex: 1, minHeight: 18, marginVertical: 3, borderRadius: 1, backgroundColor: '#ece7f6' },
  stepLineDone: { backgroundColor: '#8fe0c4' },
  stepBody: { flex: 1, flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingBottom: 16 },
  stepLabel: { color: '#a29cbc', fontSize: 15, lineHeight: 22, fontWeight: '500' },
  stepLabelDone: { color: INK, fontWeight: '700' },
  stepLabelNow: { color: '#e2477a', fontWeight: '800' },
  nowHalo: {
    position: 'absolute',
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#f47b4d',
  },
  nowCore: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 7,
    borderColor: '#f47b4d',
    backgroundColor: '#ffffff',
  },
  nowTag: {
    marginTop: 2,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#ffe9e0',
  },
  nowTagText: { color: '#d4552e', fontSize: 11, fontWeight: '800' },

  payHead: { flexDirection: 'row', alignItems: 'flex-end', flexWrap: 'wrap', gap: 6 },
  payBig: { color: INK, fontSize: 30, lineHeight: 36, fontWeight: '800', letterSpacing: -0.6 },
  payOf: { color: MUTED, fontSize: 14, marginBottom: 5 },
  payTrack: {
    height: 10,
    marginTop: 12,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: '#f1edf8',
  },
  payFill: { height: '100%', borderRadius: 5, overflow: 'hidden' },
  payTiles: { flexDirection: 'row', gap: 10, marginTop: 14 },
  payTile: { flex: 1, padding: 12, borderRadius: 16, gap: 4 },
  payTileAdvance: { backgroundColor: '#fff6ef' },
  payTileBalance: { backgroundColor: '#f4f0ff' },
  payTileLabel: { color: MUTED, fontSize: 12, fontWeight: '600' },
  payTileValue: { color: INK, fontSize: 17, lineHeight: 22, fontWeight: '800' },
  tag: { alignSelf: 'flex-start', marginTop: 2, paddingVertical: 2, paddingHorizontal: 8, borderRadius: 6 },
  tagText: { fontSize: 11, fontWeight: '800' },
  tagPaid: { backgroundColor: '#dff6ec' },
  tagPaidText: { color: '#0e8a68' },
  tagCash: { backgroundColor: '#ffe9cc' },
  tagCashText: { color: '#b35a07' },
  tagDue: { backgroundColor: '#ffe3e3' },
  tagDueText: { color: '#c2373b' },
  tagLater: { backgroundColor: '#e9e3ff' },
  tagLaterText: { color: '#5a35e0' },
  payFoot: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: LINE,
  },
  payFootText: { flex: 1, color: MUTED, fontSize: 13 },

  task: { flexDirection: 'row', gap: 12, paddingVertical: 10 },
  taskDivider: { borderTopWidth: 1, borderTopColor: LINE },
  taskBar: { width: 4, borderRadius: 2 },
  taskBody: { flex: 1 },
  taskHead: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  taskTitle: { flex: 1, color: INK, fontSize: 15, fontWeight: '600' },
  taskPill: { paddingVertical: 3, paddingHorizontal: 9, borderRadius: 999 },
  taskPillText: { fontSize: 11, fontWeight: '800' },
  taskMeta: { color: MUTED, fontSize: 12.5, marginTop: 3 },

  log: { flexDirection: 'row', gap: 12 },
  logRail: { alignItems: 'center', width: 14, paddingTop: 5 },
  logDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#d9d1f1',
  },
  logDotLatest: { width: 14, height: 14, borderRadius: 7 },
  logLine: { width: 2, flex: 1, marginVertical: 3, backgroundColor: LINE },
  logBody: { flex: 1, paddingBottom: 14 },
  logLabel: { color: INK, fontSize: 14.5, fontWeight: '600' },
  logLabelLatest: { fontWeight: '800' },
  logNote: { color: MUTED, fontSize: 13, marginTop: 2 },
  logAt: { color: '#a29cbc', fontSize: 12, marginTop: 3 },
});

/* The Guest invitation tab. */
const SERIF = Platform.select({ ios: 'Georgia', android: 'serif' });

export const inviteUi = StyleSheet.create({
  wrap: { paddingHorizontal: spacing.md, paddingTop: 22, gap: 16 },

  poster: {
    minHeight: 250,
    borderRadius: 26,
    overflow: 'hidden',
    justifyContent: 'center',
    backgroundColor: '#fff7f1',
    ...lift,
  },
  posterFill: { ...StyleSheet.absoluteFill },
  posterImage: { ...StyleSheet.absoluteFill, width: '100%', height: '100%' },
  posterShade: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(20,10,40,0.45)' },
  posterBorder: {
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
    bottom: 10,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: 'rgba(196,160,110,0.55)',
  },
  posterConfetti: { position: 'absolute', top: -6, right: -6, width: 150, height: 120, opacity: 0.8 },
  posterBody: { alignItems: 'center', paddingVertical: 34, paddingHorizontal: 30 },
  posterEyebrow: {
    color: '#b08a55',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2.4,
    textAlign: 'center',
  },
  posterHosts: {
    fontFamily: SERIF,
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 10,
    color: INK,
  },
  posterRule: { width: 46, height: 2, borderRadius: 1, marginVertical: 12 },
  posterRuleOnPhoto: { backgroundColor: 'rgba(255,255,255,0.8)' },
  posterMeta: { color: INK, fontSize: 14, fontWeight: '700', textAlign: 'center' },
  posterVenue: { color: MUTED, fontSize: 13, textAlign: 'center', marginTop: 4 },
  onPhoto: { color: '#ffffff' },
  onPhotoMuted: { color: 'rgba(255,255,255,0.85)' },
  videoBadge: {
    position: 'absolute',
    top: 18,
    right: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(20,10,40,0.6)',
  },
  videoBadgeText: { color: '#ffffff', fontSize: 11, fontWeight: '700' },

  ribbon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    ...lift,
  },
  statusLine: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 4 },
  mainButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 54,
    borderRadius: 27,
    overflow: 'hidden',
    backgroundColor: '#f47b4d',
  },
  mainButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  ribbonIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ribbonText: { flex: 1 },
  ribbonTitle: { color: INK, fontSize: 15.5, fontWeight: '800' },
  ribbonBody: { color: MUTED, fontSize: 13, lineHeight: 18, marginTop: 2 },

  card: { borderRadius: 22, padding: spacing.md, backgroundColor: '#ffffff', ...lift },
  cardHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  cardTitle: { color: INK, fontSize: 17, fontWeight: '800' },
  cardAside: {
    color: '#0e8a68',
    fontSize: 12,
    fontWeight: '800',
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: 999,
    backgroundColor: '#dff6ec',
    overflow: 'hidden',
  },
  statRow: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 14 },
  statCell: { alignItems: 'center', gap: 6 },
  statNum: { color: INK, fontSize: 15, fontWeight: '800' },
  statLabel: { color: MUTED, fontSize: 12, fontWeight: '600' },
  hint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 14,
    padding: 10,
    borderRadius: 12,
    backgroundColor: '#fff4e6',
  },
  hintText: { flex: 1, color: '#8a4a0a', fontSize: 12.5 },
  emptyGuests: { alignItems: 'center', gap: 10, paddingTop: 12 },
  emptyIcon: {
    width: 60,
    height: 60,
    borderRadius: 22,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: { color: MUTED, fontSize: 14, lineHeight: 20, textAlign: 'center', paddingHorizontal: 8 },

  actions: { flexDirection: 'row', gap: 12 },
  action: {
    flex: 1,
    minHeight: 132,
    padding: 14,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    ...lift,
  },
  actionPrimary: { backgroundColor: '#f47b4d' },
  actionIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIconPrimary: { backgroundColor: 'rgba(255,255,255,0.22)' },
  actionTitle: { color: INK, fontSize: 15, fontWeight: '800', marginTop: 12 },
  actionBody: { color: MUTED, fontSize: 12.5, lineHeight: 17, marginTop: 3 },
  actionArrow: { position: 'absolute', top: 14, right: 14 },

  sub: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 11 },
  subDivider: { borderTopWidth: 1, borderTopColor: LINE },
  subDot: { width: 12, height: 12, borderRadius: 6, overflow: 'hidden' },
  subText: { flex: 1 },
  subName: { color: INK, fontSize: 15, fontWeight: '700' },
  subMeta: { color: MUTED, fontSize: 12.5, marginTop: 2 },
});

/* The pinned header: a frosted bar with the way back, the name and the tabs. */
export const pinnedStyles = StyleSheet.create({
  bar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingBottom: 10,
    backgroundColor: 'rgba(248,245,251,0.97)',
    borderBottomWidth: 1,
    borderBottomColor: LINE,
    ...Platform.select({
      ios: {
        shadowColor: '#3a2470',
        shadowOpacity: 0.08,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
      },
      android: { elevation: 4 },
    }),
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: spacing.sm },
  back: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  title: { flex: 1, color: INK, fontSize: 17, fontWeight: '800' },
  tabs: { marginTop: 6 },
});

/* The in-page tab row, under the stats card. */
export const tabsWrap = StyleSheet.create({
  wrap: { marginTop: 18 },
});
