import { Platform, StyleSheet } from 'react-native';
import { globalStyles } from '../../styles/globalStyles';
import { colors, spacing } from '../../theme';
import {
  PLAN_ACCENT,
  PLAN_ACCENT_SOFT,
  PLAN_BG,
  PLAN_BORDER,
  PLAN_GREEN,
  PLAN_GREEN_SOFT,
  PLAN_NAVY,
  PLAN_NAVY_DEEP,
  PLAN_QUOTE_BG,
  PLAN_TEXT_MUTED,
} from './constants';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: PLAN_BG },
  body: { flex: 1 },
  scroll: { flex: 1 },
  content: { padding: spacing.md, paddingBottom: spacing.xl },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.lg, backgroundColor: PLAN_BG },
  loadingText: { color: PLAN_TEXT_MUTED, marginTop: spacing.md },
  errorText: { color: colors.danger, textAlign: 'center' },
  retryButton: { marginTop: spacing.lg },
  footerBar: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    backgroundColor: PLAN_BG,
  },
  floatingButton: {
    borderRadius: 999,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 6 } },
      android: { elevation: 4 },
    }),
  },
  blockReasonText: { color: colors.danger, textAlign: 'center', marginBottom: spacing.sm },
  fixedHeader: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    backgroundColor: PLAN_BG,
    borderBottomWidth: 1,
    borderBottomColor: PLAN_BORDER,
  },
  successCard: { ...globalStyles.card, padding: spacing.lg, alignItems: 'center' },
  successTitle: { color: PLAN_NAVY, marginTop: spacing.md, textAlign: 'center' },
  successSubtitle: { color: PLAN_TEXT_MUTED, textAlign: 'center', marginTop: spacing.sm },
  newPlanButton: { marginTop: spacing.lg },
});

// Web's PlanHero.module.css: a dark navy card with an orange eyebrow/accent —
// the same hero treatment Home's Banner already ports from the same design.
export const heroStyles = StyleSheet.create({
  section: { marginBottom: spacing.lg, backgroundColor: PLAN_NAVY_DEEP, borderRadius: 16, padding: spacing.md },
  heading: { color: colors.onPrimary },
  headingAccent: { color: '#ff8b5e' },
  subtitle: { color: 'rgba(255,255,255,0.74)', marginTop: 2 },
  trustRow: { marginTop: spacing.sm },
  trustChip: {
    ...globalStyles.row,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    gap: spacing.xs,
    marginRight: spacing.xs,
  },
  trustLabel: { color: 'rgba(255,255,255,0.85)' },
  plainSection: { marginBottom: spacing.lg },
  plainHeading: { color: PLAN_NAVY },
  plainSubtitle: { color: PLAN_TEXT_MUTED, marginTop: spacing.xs },
});

export const stepperStyles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'flex-start' },
  item: { flex: 1, alignItems: 'center' },
  dot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: PLAN_BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  dotCurrent: { borderColor: PLAN_ACCENT, backgroundColor: PLAN_ACCENT },
  dotDone: { borderColor: PLAN_ACCENT, backgroundColor: colors.background },
  dotNumber: { color: PLAN_TEXT_MUTED, fontSize: 11, fontWeight: '700' },
  dotNumberCurrent: { color: colors.onPrimary },
  dotNumberDone: { color: PLAN_ACCENT },
  line: { flex: 1, height: 2, marginTop: 12, backgroundColor: PLAN_BORDER },
  lineDone: { backgroundColor: PLAN_ACCENT },
  label: { color: PLAN_TEXT_MUTED, marginTop: spacing.xs, textAlign: 'center' },
  labelCurrent: { color: PLAN_NAVY, fontWeight: '700' },
});

export const occasionPickerStyles = StyleSheet.create({
  section: { marginBottom: spacing.lg },
  sectionTitle: { color: PLAN_NAVY, marginBottom: spacing.md },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  card: {
    width: 100,
    height: 108,
    borderRadius: 16,
    padding: spacing.sm,
    justifyContent: 'space-between',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  cardSelected: { borderColor: PLAN_ACCENT },
  cardBackground: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  artLayer: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  iconBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  check: {
    position: 'absolute',
    top: spacing.xs,
    right: spacing.xs,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: PLAN_ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  label: { color: colors.onPrimary, fontWeight: '700' },
});

// Web's EventDetailsForm.module.css `.control`: a single bordered pill with an
// icon + borderless input inside — NOT an input with its own border nested in
// another border. controlInput cancels EventlyTextInput's own base border/
// padding so controlRow supplies the one visible outline.
export const eventDetailsStyles = StyleSheet.create({
  section: { marginBottom: spacing.lg },
  field: { marginBottom: spacing.md },
  label: { color: PLAN_NAVY, marginBottom: spacing.xs, fontWeight: '600' },
  controlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    borderWidth: 1.5,
    borderColor: PLAN_BORDER,
    borderRadius: 14,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
    backgroundColor: colors.background,
  },
  controlRowFocused: { borderColor: PLAN_ACCENT },
  controlInput: {
    flex: 1,
    color: PLAN_NAVY,
    fontSize: 15,
    fontWeight: '600',
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  dateValue: { flex: 1, color: PLAN_NAVY, fontWeight: '600' },
  dateValuePlaceholder: { flex: 1, color: PLAN_TEXT_MUTED, fontWeight: '400' },
  banner: {
    ...globalStyles.row,
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: PLAN_GREEN_SOFT,
    borderRadius: 12,
    padding: spacing.md,
  },
  bannerText: { color: PLAN_TEXT_MUTED, flex: 1 },
  bannerBold: { fontWeight: '700', color: PLAN_NAVY },
});

export const dateModalStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
  card: { backgroundColor: colors.background, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: spacing.lg },
  headRow: { ...globalStyles.row, justifyContent: 'space-between', marginBottom: spacing.md },
  monthLabel: { color: PLAN_NAVY },
  navButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: PLAN_BG, alignItems: 'center', justifyContent: 'center' },
  navButtonDisabled: { opacity: 0.3 },
  weekdayRow: { flexDirection: 'row' },
  weekday: { flex: 1, textAlign: 'center', color: PLAN_TEXT_MUTED },
  dayGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: spacing.sm },
  dayCell: { width: `${100 / 7}%`, aspectRatio: 1, alignItems: 'center', justifyContent: 'center' },
  dayCircle: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  daySelected: { backgroundColor: PLAN_ACCENT },
  dayText: { color: PLAN_NAVY },
  dayTextDisabled: { color: PLAN_BORDER },
  dayTextSelected: { color: colors.onPrimary, fontWeight: '700' },
  doneButton: { marginTop: spacing.lg },
});

// A single reusable bottom-sheet list — City (with free-text search), Guests
// and Budget all pick from this instead of inline chip rows/dropdowns, which
// read as a ported web control rather than a native mobile picker.
export const selectModalStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
  card: { backgroundColor: colors.background, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: spacing.lg, maxHeight: '75%' },
  headRow: { ...globalStyles.row, justifyContent: 'space-between', marginBottom: spacing.md },
  title: { color: PLAN_NAVY },
  closeButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: PLAN_BG, alignItems: 'center', justifyContent: 'center' },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    borderWidth: 1.5,
    borderColor: PLAN_BORDER,
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  searchInput: {
    flex: 1,
    color: PLAN_NAVY,
    fontSize: 15,
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  optionRow: {
    ...globalStyles.row,
    justifyContent: 'space-between',
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: PLAN_BORDER,
  },
  optionRowFirst: { borderTopWidth: 0 },
  optionText: { color: PLAN_NAVY },
  optionTextSelected: { color: PLAN_ACCENT, fontWeight: '700' },
  clearRow: {
    ...globalStyles.row,
    gap: spacing.xs,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: PLAN_BORDER,
    marginBottom: spacing.xs,
  },
  clearText: { color: PLAN_TEXT_MUTED, fontStyle: 'italic' },
  emptyText: { color: PLAN_TEXT_MUTED, textAlign: 'center', paddingVertical: spacing.lg },
});

export const ideasStyles = StyleSheet.create({
  section: { marginBottom: spacing.lg },
  head: { ...globalStyles.row, gap: spacing.sm, marginBottom: spacing.xs },
  icon: { width: 26, height: 26, borderRadius: 13, backgroundColor: PLAN_ACCENT_SOFT, alignItems: 'center', justifyContent: 'center' },
  title: { color: PLAN_NAVY, fontWeight: '600' },
  subtitle: { color: PLAN_TEXT_MUTED, marginBottom: spacing.sm },
  chipRow: { marginBottom: spacing.sm },
  chip: {
    ...globalStyles.row,
    gap: 4,
    borderWidth: 1.5,
    borderColor: PLAN_BORDER,
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    marginRight: spacing.xs,
    backgroundColor: colors.background,
  },
  chipText: { color: PLAN_NAVY },
  textarea: {
    borderWidth: 1.5,
    borderColor: PLAN_BORDER,
    borderRadius: 14,
    padding: spacing.md,
    color: PLAN_NAVY,
    minHeight: 80,
    textAlignVertical: 'top',
    backgroundColor: colors.background,
  },
});

export const categoriesStepStyles = StyleSheet.create({
  section: { marginBottom: spacing.lg },
  head: { ...globalStyles.row, justifyContent: 'space-between', marginBottom: spacing.xs },
  title: { color: PLAN_NAVY, flex: 1, marginRight: spacing.sm },
  subtitle: { color: PLAN_TEXT_MUTED, marginBottom: spacing.md },
  counterPill: { backgroundColor: PLAN_ACCENT_SOFT, borderRadius: 999, paddingHorizontal: spacing.sm, paddingVertical: 4 },
  counter: { color: PLAN_ACCENT, fontWeight: '700' },
  // A single-column checklist — each row a full-width tappable card with a
  // trailing checkmark circle, the native mobile pattern for multi-select
  // (vs. a 2-column bordered-box grid, which reads as a ported web grid).
  list: { gap: spacing.sm },
  row: {
    ...globalStyles.card,
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  // Selection reads through the tint + filled checkmark alone — no heavy
  // outline, so a screen with several rows selected doesn't turn into a wall
  // of bold orange borders.
  rowSelected: { backgroundColor: PLAN_ACCENT_SOFT },
  icon: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  textCol: { flex: 1 },
  rowTitle: { color: PLAN_NAVY },
  rowSubtitle: { color: PLAN_TEXT_MUTED, marginTop: 1 },
  checkCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: PLAN_BORDER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkCircleOn: { backgroundColor: PLAN_ACCENT, borderColor: PLAN_ACCENT },
  addRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    borderWidth: 1.5,
    borderColor: PLAN_BORDER,
    borderStyle: 'dashed',
    borderRadius: 14,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
    marginTop: spacing.xs,
    backgroundColor: colors.background,
  },
  addInput: {
    flex: 1,
    color: PLAN_NAVY,
    fontSize: 15,
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  addButton: { width: 28, height: 28, borderRadius: 14, backgroundColor: PLAN_ACCENT, alignItems: 'center', justifyContent: 'center' },
});

export const organizersStyles = StyleSheet.create({
  section: { marginBottom: spacing.lg },
  toolsRow: { ...globalStyles.row, justifyContent: 'space-between', marginBottom: spacing.sm },
  resultCount: { color: PLAN_NAVY, flex: 1 },
  filterButton: {
    ...globalStyles.row,
    gap: spacing.xs,
    borderWidth: 1.5,
    borderColor: PLAN_BORDER,
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  filterButtonActive: { borderColor: PLAN_ACCENT, backgroundColor: PLAN_ACCENT },
  filterButtonText: { color: PLAN_NAVY },
  filterButtonTextActive: { color: colors.onPrimary },
  sortRow: { gap: spacing.sm, paddingBottom: spacing.md },
  sortChip: {
    borderWidth: 1.5,
    borderColor: PLAN_BORDER,
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    marginRight: spacing.sm,
  },
  sortChipActive: { borderColor: PLAN_ACCENT, backgroundColor: PLAN_ACCENT },
  sortChipText: { color: PLAN_NAVY },
  sortChipTextActive: { color: colors.onPrimary },
  list: { gap: spacing.md },
  card: { ...globalStyles.card, padding: spacing.md },
  cardMuted: { opacity: 0.6 },
  topRow: { ...globalStyles.row, alignItems: 'flex-start', gap: spacing.sm },
  avatar: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: colors.onPrimary },
  idCol: { flex: 1 },
  nameRow: { ...globalStyles.row, flexWrap: 'wrap', gap: spacing.xs },
  name: { color: PLAN_NAVY },
  tierBadge: { ...globalStyles.row, gap: 3, borderRadius: 999, paddingHorizontal: spacing.sm, paddingVertical: 2 },
  tierBadgeText: { color: colors.onPrimary, fontWeight: '700' },
  conciergePill: { ...globalStyles.row, gap: 3, backgroundColor: PLAN_NAVY_DEEP, borderRadius: 999, paddingHorizontal: spacing.sm, paddingVertical: 2 },
  conciergeText: { color: colors.onPrimary, fontWeight: '700' },
  scorePill: { ...globalStyles.row, gap: 3, backgroundColor: PLAN_ACCENT_SOFT, borderRadius: 999, paddingHorizontal: spacing.sm, paddingVertical: 2 },
  scoreText: { color: PLAN_ACCENT, fontWeight: '700' },
  ratingRow: { ...globalStyles.row, gap: spacing.xs, marginTop: spacing.xs },
  ratingText: { color: PLAN_NAVY },
  reviewsText: { color: PLAN_TEXT_MUTED },
  metaText: { color: PLAN_TEXT_MUTED, marginTop: 2 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginTop: spacing.sm },
  tag: { backgroundColor: PLAN_BG, borderRadius: 8, paddingHorizontal: spacing.sm, paddingVertical: 2 },
  tagText: { color: PLAN_TEXT_MUTED },
  reasons: { marginTop: spacing.sm, gap: 4 },
  reasonRow: { ...globalStyles.row, gap: spacing.xs },
  reasonText: { color: PLAN_NAVY, flex: 1 },
  matchRow: { ...globalStyles.row, gap: spacing.xs, marginTop: spacing.sm },
  matchText: { color: PLAN_NAVY },
  estRow: { marginTop: spacing.sm, borderTopWidth: 1, borderTopColor: PLAN_BORDER, paddingTop: spacing.sm },
  estLabel: { color: PLAN_TEXT_MUTED, fontSize: 10, letterSpacing: 0.5 },
  estValue: { color: PLAN_NAVY, marginTop: 2 },
  unavailRow: { ...globalStyles.row, gap: spacing.xs },
  unavailText: { color: colors.danger },
  actionsRow: { marginTop: spacing.md },
  selectButton: {},
  emptyState: { ...globalStyles.card, padding: spacing.lg, alignItems: 'center' },
  emptyTitle: { color: PLAN_NAVY, marginTop: spacing.md, textAlign: 'center' },
  emptyMessage: { color: PLAN_TEXT_MUTED, marginTop: spacing.sm, textAlign: 'center' },
  emptyButton: { marginTop: spacing.md },
});

export const filterModalStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
  card: { backgroundColor: colors.background, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: spacing.lg, maxHeight: '80%' },
  headRow: { ...globalStyles.row, justifyContent: 'space-between', marginBottom: spacing.md },
  title: { color: PLAN_NAVY },
  closeButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: PLAN_BG, alignItems: 'center', justifyContent: 'center' },
  groupLabel: { color: PLAN_TEXT_MUTED, letterSpacing: 0.5, marginTop: spacing.md, marginBottom: spacing.sm },
  checkRow: { ...globalStyles.row, gap: spacing.sm, paddingVertical: spacing.xs },
  checkbox: { width: 20, height: 20, borderRadius: 6, borderWidth: 2, borderColor: PLAN_BORDER, alignItems: 'center', justifyContent: 'center' },
  checkboxOn: { backgroundColor: PLAN_ACCENT, borderColor: PLAN_ACCENT },
  checkLabel: { color: PLAN_NAVY },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  pill: { borderWidth: 1.5, borderColor: PLAN_BORDER, borderRadius: 999, paddingHorizontal: spacing.md, paddingVertical: spacing.xs },
  pillOn: { borderColor: PLAN_ACCENT, backgroundColor: PLAN_ACCENT },
  pillText: { color: PLAN_NAVY },
  pillTextOn: { color: colors.onPrimary },
  footerRow: { ...globalStyles.row, gap: spacing.md, marginTop: spacing.lg },
  clearButton: { flex: 1 },
  applyButton: { flex: 1 },
});

export const reviewStyles = StyleSheet.create({
  section: { marginBottom: spacing.lg },
  // One consolidated "receipt" card (Event details / Categories / Organizer as
  // internal sections) instead of three separate floating panels — reads as a
  // single mobile order-review summary rather than a stack of dashboard cards.
  summaryCard: { ...globalStyles.card, padding: spacing.md },
  sectionBlock: { paddingVertical: spacing.md },
  sectionBlockFirst: { paddingTop: 0 },
  sectionDivider: { height: 1, backgroundColor: PLAN_BORDER },
  panelHead: { ...globalStyles.row, justifyContent: 'space-between', marginBottom: spacing.sm },
  panelTitle: { color: PLAN_NAVY },
  editButton: { ...globalStyles.row, gap: 4 },
  editText: { color: PLAN_ACCENT },
  // A 2-column key/value grid reads like a checkout summary — lighter than a
  // vertical list of icon-badged rows repeated six times.
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  detailItem: { width: '50%', marginBottom: spacing.sm, paddingRight: spacing.sm },
  detailItemFull: { width: '100%', marginBottom: spacing.sm },
  rowLabel: { color: PLAN_TEXT_MUTED },
  rowValue: { color: PLAN_NAVY, marginTop: 1 },
  rowValueMuted: { color: PLAN_TEXT_MUTED },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  chip: { ...globalStyles.row, gap: 4, backgroundColor: PLAN_BG, borderRadius: 999, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  chipText: { color: PLAN_NAVY },
  emptyText: { color: PLAN_TEXT_MUTED },
  orgRow: { ...globalStyles.row, gap: spacing.sm, marginTop: spacing.sm },
  orgAvatar: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  orgAvatarText: { color: colors.onPrimary },
  orgMeta: { flex: 1 },
  orgName: { color: PLAN_NAVY },
  orgSub: { ...globalStyles.row, gap: 4, color: PLAN_TEXT_MUTED },
  orgSubText: { color: PLAN_TEXT_MUTED },
  orgTag: { backgroundColor: PLAN_ACCENT_SOFT, color: PLAN_ACCENT, borderRadius: 999, paddingHorizontal: spacing.sm, paddingVertical: 2, fontWeight: '700' },
  nextPanel: { ...globalStyles.card, padding: spacing.md, marginBottom: spacing.md },
  nextPanelTitle: { color: PLAN_NAVY, marginBottom: spacing.sm },
  nextRow: { ...globalStyles.row, alignItems: 'flex-start', gap: spacing.sm, marginBottom: spacing.sm },
  nextTextCol: { flex: 1 },
  nextIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: PLAN_ACCENT_SOFT, alignItems: 'center', justifyContent: 'center' },
  nextTitle: { color: PLAN_NAVY },
  nextDesc: { color: PLAN_TEXT_MUTED, marginTop: 1 },
  quoteBox: {
    ...globalStyles.row,
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: PLAN_QUOTE_BG,
    borderRadius: 12,
    padding: spacing.sm,
    marginTop: spacing.sm,
  },
  quoteTextCol: { flex: 1 },
  quoteTitle: { color: PLAN_NAVY },
  quoteText: { color: PLAN_TEXT_MUTED, marginTop: 1 },
  submitCard: { ...globalStyles.card, padding: spacing.md },
  submitTitle: { color: PLAN_NAVY },
  submitText: { color: PLAN_TEXT_MUTED, marginTop: spacing.xs, marginBottom: spacing.md },
  savedRow: { ...globalStyles.row, gap: spacing.xs, marginBottom: spacing.sm },
  savedText: { color: PLAN_GREEN },
  errorBox: { ...globalStyles.row, alignItems: 'flex-start', gap: spacing.xs, backgroundColor: '#FEF2F2', borderRadius: 12, padding: spacing.sm, marginBottom: spacing.md },
  errorText: { color: colors.danger, flex: 1 },
  submitButton: {
    borderRadius: 999,
    ...Platform.select({
      ios: { shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 6 } },
      android: { elevation: 4 },
    }),
  },
  footnoteRow: { ...globalStyles.row, gap: spacing.xs, marginTop: spacing.md },
  footnoteText: { color: PLAN_TEXT_MUTED, flex: 1 },
});
