import { Platform, StyleSheet } from 'react-native';
import { globalStyles } from '../../styles/globalStyles';
import { colors, spacing } from '../../theme';
import {
  REG_ACCENT,
  REG_ACCENT_SOFT,
  REG_BG,
  REG_BORDER,
  REG_GREEN_DARK,
  REG_GREEN_SOFT,
  REG_NAVY,
  REG_TEXT_MUTED,
} from './constants';

export const screenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: REG_BG },
  centerFill: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.sm, padding: spacing.xl },
  centerText: { color: REG_TEXT_MUTED, textAlign: 'center' },
  web: { flex: 1 },
});

export const authGateStyles = StyleSheet.create({
  flex: { flex: 1 },
  content: { flexGrow: 1, padding: spacing.lg, paddingTop: spacing.xl * 1.2 },
  badge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#fdeee7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  title: { color: REG_NAVY },
  subtitle: { color: REG_TEXT_MUTED, marginTop: spacing.xs, marginBottom: spacing.lg },
  form: { gap: spacing.md },
  label: { color: REG_NAVY },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 54,
    borderWidth: 1.5,
    borderColor: REG_BORDER,
    borderRadius: 16,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
    backgroundColor: colors.surface,
  },
  dialCode: { color: REG_NAVY, paddingRight: spacing.sm, borderRightWidth: 1, borderRightColor: REG_BORDER },
  phoneInput: { flex: 1, color: REG_NAVY, fontSize: 17, fontWeight: '600', letterSpacing: 0.5, borderWidth: 0, backgroundColor: 'transparent', paddingHorizontal: 0 },
  backRow: { ...globalStyles.row, gap: spacing.xs, marginBottom: spacing.xs },
  backText: { color: REG_ACCENT },
  sentTo: { color: REG_TEXT_MUTED, marginBottom: spacing.xs },
  otpRow: { flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' },
  otpBox: {
    flex: 1,
    height: 54,
    borderWidth: 1.5,
    borderColor: REG_BORDER,
    borderRadius: 14,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
    color: REG_NAVY,
    backgroundColor: colors.surface,
  },
  otpBoxFilled: { borderColor: REG_ACCENT, backgroundColor: colors.background },
  devHint: { color: REG_TEXT_MUTED, textAlign: 'center' },
  error: { color: colors.danger },
  button: {
    borderRadius: 999,
    ...Platform.select({
      ios: { shadowColor: REG_ACCENT, shadowOpacity: 0.3, shadowRadius: 10, shadowOffset: { width: 0, height: 5 } },
      android: { elevation: 3 },
    }),
  },
  resendMuted: { color: REG_TEXT_MUTED, textAlign: 'center' },
  resendActive: { textAlign: 'center', fontWeight: '700' },
});

export const signupStyles = StyleSheet.create({
  flex: { flex: 1 },
  content: { padding: spacing.lg, paddingBottom: spacing.xl * 1.5, gap: spacing.lg },
  title: { color: REG_NAVY },
  subtitle: { color: REG_TEXT_MUTED, marginTop: -spacing.sm },
  row: { flexDirection: 'row', gap: spacing.sm },
  half: { flex: 1 },
  field: { gap: spacing.xs },
  label: { color: REG_NAVY },
  input: { borderColor: REG_BORDER, backgroundColor: colors.surface, borderRadius: 14 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  chip: {
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: REG_BORDER,
    backgroundColor: colors.surface,
  },
  chipOn: { borderColor: REG_ACCENT, backgroundColor: REG_ACCENT_SOFT },
  chipText: { color: REG_NAVY },
  chipTextOn: { color: REG_ACCENT, fontWeight: '700' },
  note: {
    ...globalStyles.row,
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: REG_GREEN_SOFT,
    borderRadius: 14,
    padding: spacing.md,
  },
  noteText: { color: REG_GREEN_DARK, flex: 1 },
  error: { color: colors.danger },
  button: { borderRadius: 999 },
});
