import { Platform, StyleSheet } from 'react-native';
import { globalStyles } from '../../styles/globalStyles';
import { colors, spacing } from '../../theme';
import { ORG_ACCENT, ORG_BG, ORG_BORDER, ORG_DANGER, ORG_GREEN, ORG_GREEN_DARK, ORG_GREEN_SOFT, ORG_NAVY, ORG_TEXT_MUTED } from './constants';

export const screenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: ORG_BG },
  scroll: { flex: 1 },
  content: { padding: spacing.lg, paddingBottom: spacing.xl, gap: spacing.lg },
  stepTitle: { color: ORG_NAVY },
  stepSubtitle: { color: ORG_TEXT_MUTED, marginTop: -spacing.sm },
  stepBody: { gap: spacing.md },
  stepBodyWide: { gap: spacing.md + 2 },
  centerFill: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.sm },
  centerText: { color: ORG_TEXT_MUTED, textAlign: 'center', paddingHorizontal: spacing.xl },
  basicNote: { marginTop: spacing.sm },
  savedHint: { color: ORG_TEXT_MUTED, textAlign: 'right' },
  formErrorBox: {
    ...globalStyles.row,
    alignItems: 'flex-start',
    gap: spacing.xs,
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    padding: spacing.sm,
  },
  formErrorText: { color: colors.danger, flex: 1 },
  noteBox: {
    ...globalStyles.row,
    alignItems: 'flex-start',
    gap: spacing.sm,
    backgroundColor: ORG_GREEN_SOFT,
    borderRadius: 14,
    padding: spacing.md,
  },
  noteText: { color: ORG_GREEN_DARK, flex: 1 },
  footerBar: {
    ...globalStyles.row,
    gap: spacing.sm,
    padding: spacing.md,
    paddingBottom: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: ORG_BORDER,
    backgroundColor: colors.background,
  },
  footerButton: { flex: 1 },
});

export const authGateStyles = StyleSheet.create({
  flex: { flex: 1 },
  content: { flexGrow: 1, padding: spacing.lg, paddingTop: spacing.xl * 1.2 },
  badge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#fdeee7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  title: { color: ORG_NAVY },
  subtitle: { color: ORG_TEXT_MUTED, marginTop: spacing.xs, marginBottom: spacing.lg },
  form: { gap: spacing.md },
  label: { color: ORG_NAVY },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 54,
    borderWidth: 1.5,
    borderColor: ORG_BORDER,
    borderRadius: 16,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
    backgroundColor: colors.surface,
  },
  dialCode: { color: ORG_NAVY, paddingRight: spacing.sm, borderRightWidth: 1, borderRightColor: ORG_BORDER },
  phoneInput: { flex: 1, color: ORG_NAVY, fontSize: 17, fontWeight: '600', letterSpacing: 0.5, borderWidth: 0, backgroundColor: 'transparent', paddingHorizontal: 0 },
  backRow: { ...globalStyles.row, gap: spacing.xs, marginBottom: spacing.xs },
  backText: { color: ORG_ACCENT },
  sentTo: { color: ORG_TEXT_MUTED, marginBottom: spacing.xs },
  otpRow: { flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' },
  otpBox: {
    flex: 1,
    height: 54,
    borderWidth: 1.5,
    borderColor: ORG_BORDER,
    borderRadius: 14,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
    color: ORG_NAVY,
    backgroundColor: colors.surface,
  },
  otpBoxFilled: { borderColor: ORG_ACCENT, backgroundColor: colors.background },
  devHint: { color: ORG_TEXT_MUTED, textAlign: 'center' },
  error: { color: colors.danger },
  button: {
    borderRadius: 999,
    ...Platform.select({
      ios: { shadowColor: ORG_ACCENT, shadowOpacity: 0.3, shadowRadius: 10, shadowOffset: { width: 0, height: 5 } },
      android: { elevation: 3 },
    }),
  },
  resendMuted: { color: ORG_TEXT_MUTED, textAlign: 'center' },
  resendActive: { textAlign: 'center', fontWeight: '700' },
});

export const stepProgressStyles = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'flex-start', paddingHorizontal: spacing.lg, paddingTop: spacing.md },
  item: { flex: 1, alignItems: 'center' },
  lineWrap: { flexDirection: 'row', alignItems: 'center', width: '100%' },
  line: { flex: 1, height: 2, backgroundColor: ORG_BORDER },
  lineHidden: { opacity: 0 },
  lineDone: { backgroundColor: ORG_GREEN },
  circle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: ORG_BORDER,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  circleCurrent: { borderColor: ORG_ACCENT, backgroundColor: '#fdeee7' },
  circleDone: { borderColor: ORG_GREEN, backgroundColor: ORG_GREEN },
  circleText: { fontSize: 12, fontWeight: '700', color: ORG_TEXT_MUTED },
  circleTextCurrent: { color: ORG_ACCENT },
  label: { fontSize: 10, color: ORG_TEXT_MUTED, marginTop: spacing.xs, textAlign: 'center' },
  labelCurrent: { color: ORG_ACCENT, fontWeight: '700' },
  labelDone: { color: ORG_GREEN, fontWeight: '700' },
});

export const fieldStyles = StyleSheet.create({
  group: { gap: spacing.xs },
  row: { flexDirection: 'row', gap: spacing.sm },
  half: { flex: 1 },
  label: { color: ORG_NAVY },
  optional: { color: ORG_TEXT_MUTED },
  input: { borderColor: ORG_BORDER, backgroundColor: colors.surface, borderRadius: 14 },
  inputError: { borderColor: ORG_DANGER },
  textarea: { borderColor: ORG_BORDER, backgroundColor: colors.surface, borderRadius: 14, minHeight: 90, textAlignVertical: 'top', paddingTop: spacing.sm },
  error: { color: ORG_DANGER },
  errorSmall: { color: ORG_DANGER, marginTop: spacing.xs },
  hint: { color: ORG_TEXT_MUTED },
  valid: { ...globalStyles.row, gap: spacing.xs },
  validText: { color: ORG_GREEN },
  readonlyRow: {
    ...globalStyles.row,
    gap: spacing.xs,
    height: 50,
    borderRadius: 14,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.surface,
  },
  readonlyText: { color: ORG_TEXT_MUTED, flex: 1 },
});

export const selectStyles = StyleSheet.create({
  control: {
    ...globalStyles.row,
    height: 50,
    borderWidth: 1.5,
    borderColor: ORG_BORDER,
    borderRadius: 14,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.surface,
    justifyContent: 'space-between',
  },
  controlText: { color: ORG_NAVY, flex: 1 },
  controlPlaceholder: { color: ORG_TEXT_MUTED, flex: 1 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  card: { backgroundColor: colors.background, borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '75%', paddingBottom: spacing.lg },
  headRow: { ...globalStyles.row, justifyContent: 'space-between', padding: spacing.md, borderBottomWidth: 1, borderBottomColor: ORG_BORDER },
  title: { color: ORG_NAVY },
  closeButton: { padding: spacing.xs },
  searchRow: { ...globalStyles.row, gap: spacing.sm, margin: spacing.md, borderWidth: 1, borderColor: ORG_BORDER, borderRadius: 12, paddingHorizontal: spacing.sm },
  searchInput: { flex: 1, borderWidth: 0, backgroundColor: 'transparent' },
  optionRow: { ...globalStyles.row, justifyContent: 'space-between', paddingVertical: spacing.md, paddingHorizontal: spacing.md, borderBottomWidth: 1, borderBottomColor: '#f3f3f1' },
  optionText: { color: ORG_NAVY },
  optionTextSelected: { color: ORG_ACCENT, fontWeight: '700' },
  emptyText: { color: ORG_TEXT_MUTED, padding: spacing.md, textAlign: 'center' },
});

export const chipStyles = StyleSheet.create({
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  chip: {
    borderWidth: 1.5,
    borderColor: ORG_BORDER,
    backgroundColor: colors.surface,
    borderRadius: 999,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
  },
  chipActive: { borderColor: ORG_ACCENT, backgroundColor: '#fdeee7' },
  chipText: { color: ORG_TEXT_MUTED },
  chipTextActive: { color: ORG_ACCENT, fontWeight: '700' },
});

export const uploadStyles = StyleSheet.create({
  tile: {
    borderWidth: 1.5,
    borderColor: ORG_BORDER,
    borderStyle: 'dashed',
    borderRadius: 16,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.md,
    gap: spacing.xs,
    minHeight: 110,
  },
  tileFilled: { borderStyle: 'solid', padding: 0, overflow: 'hidden' },
  tileImage: { width: '100%', height: 110, borderRadius: 14 },
  tileLabel: { color: ORG_NAVY },
  tileHint: { color: ORG_TEXT_MUTED, textAlign: 'center' },
  removeBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderRadius: 12,
    padding: 4,
  },
  fileBadge: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(0,0,0,0.55)', paddingVertical: 4, paddingHorizontal: 8 },
  fileBadgeText: { color: '#fff' },
  avatarWrap: { alignItems: 'center', gap: spacing.sm },
  avatarCircle: { width: 96, height: 96, borderRadius: 48, overflow: 'hidden', backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' },
  avatarImage: { width: 96, height: 96, borderRadius: 48 },
  avatarSpinner: { position: 'absolute' },
  tileLabelRow: { marginBottom: 6 },
  addTileRow: { marginBottom: 6 },
  galleryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  galleryTile: { width: '30.6%', aspectRatio: 1, borderRadius: 12, overflow: 'hidden' },
  galleryImage: { width: '100%', height: '100%' },
  galleryAddTile: {
    width: '30.6%',
    aspectRatio: 1,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: ORG_BORDER,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
});

export const categoryGridStyles = StyleSheet.create({
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  tile: {
    width: '47%',
    borderWidth: 1.5,
    borderColor: ORG_BORDER,
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: spacing.md,
    gap: spacing.xs,
  },
  tileActive: { borderColor: ORG_ACCENT, backgroundColor: '#fdeee7' },
  tileText: { color: ORG_NAVY },
  tileTextActive: { color: ORG_ACCENT, fontWeight: '700' },
});

export const sidebarStyles = StyleSheet.create({
  header: { ...globalStyles.row, justifyContent: 'space-between', paddingHorizontal: spacing.lg, paddingTop: spacing.md },
  headerTitle: { color: ORG_NAVY },
  headerStep: { color: ORG_TEXT_MUTED },
});

export const submittedStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: ORG_BG, alignItems: 'center', justifyContent: 'center', padding: spacing.xl },
  badge: { width: 84, height: 84, borderRadius: 42, backgroundColor: ORG_GREEN_SOFT, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.lg },
  title: { color: ORG_NAVY, textAlign: 'center' },
  subtitle: { color: ORG_TEXT_MUTED, textAlign: 'center', marginTop: spacing.sm, marginBottom: spacing.xl },
  button: { borderRadius: 999, alignSelf: 'stretch' },
});
