import { Platform, StyleSheet } from 'react-native';
import { colors, spacing } from '../../theme';
import {
  PE_ACCENT,
  PE_ACCENT_SOFT,
  PE_BORDER,
  PE_GREEN,
  PE_GREEN_SOFT,
  PE_LIVE,
  PE_NAVY,
} from './styles';

/*
 * The public-events screens, as designed: a cool off-white page, white cards
 * with a soft shadow, coral for every action and navy for every word.
 */
export const PE_CANVAS = '#f6f7fb';
export const PE_MUTED = '#6b7385';
export const PE_PURPLE = '#6d4df2';
export const PE_TICKET_TOP = '#1b1446';
export const PE_TICKET_BOTTOM = '#3a1d6e';

const shadow = Platform.select({
  ios: {
    shadowColor: PE_NAVY,
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  android: { elevation: 2 },
});

/** Pieces every screen shares. */
export const ui = StyleSheet.create({
  screen: { flex: 1, backgroundColor: PE_CANVAS },
  centre: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  content: { padding: spacing.md, paddingBottom: spacing.xl, gap: spacing.md },
  card: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: spacing.md,
    ...shadow,
  },
  cardTitle: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 19,
    marginBottom: spacing.s12,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  line: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  lineText: { color: PE_MUTED, fontSize: 12.5, lineHeight: 18, flexShrink: 1 },
  muted: { color: PE_MUTED, lineHeight: 18 },
  error: { color: PE_LIVE, textAlign: 'center', marginTop: spacing.sm },
  retry: { paddingHorizontal: 24, marginTop: 16 },
  flex: { flex: 1 },
  fill: { position: 'absolute', top: 0, left: 0 },
  centerText: { textAlign: 'center' },
  gapTop: { marginTop: 8 },
  sectionTitle: { marginTop: 8, marginBottom: 0 },
  spacer26: { width: 26 },
  scrollPad: { paddingBottom: 24 },
  whitePill: { backgroundColor: '#ffffff' },
  soldOutText: { color: '#d93b3b' },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: PE_BORDER,
    marginVertical: spacing.s12,
  },

  pill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  pillText: { fontWeight: '700', fontSize: 11 },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: PE_LIVE,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#ffffff' },
  livePillText: { color: '#ffffff', fontWeight: '800', fontSize: 10.5 },

  primary: {
    height: 50,
    borderRadius: 14,
    backgroundColor: PE_ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  primaryOff: { opacity: 0.5 },
  primaryText: { color: '#ffffff', fontWeight: '800', fontSize: 15 },
  outline: {
    height: 48,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: PE_ACCENT,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  outlineText: { color: PE_ACCENT, fontWeight: '700', fontSize: 14 },

  bar: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.s12,
    backgroundColor: colors.background,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: PE_BORDER,
    gap: spacing.sm,
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(14,26,51,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* The small event summary on selection and checkout. */
  mini: { flexDirection: 'row', gap: spacing.s12, alignItems: 'center' },
  miniThumb: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: '#e9edf5',
  },
  miniText: { flex: 1, gap: 4 },
  miniTitle: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 19,
  },

  /* Option sheet */
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(14,26,51,0.45)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#e3e6ee',
    marginBottom: spacing.md,
  },
  sheetTitle: { color: PE_NAVY, fontWeight: '800', marginBottom: spacing.xs },
  sheetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 48,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PE_BORDER,
  },
  sheetRowText: { color: PE_NAVY },
  sheetRowTextOn: { color: PE_ACCENT, fontWeight: '700' },
});

/** 1 — the list. */
export const listUi = StyleSheet.create({
  ticketsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: PE_ACCENT_SOFT,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  ticketsButtonText: { color: PE_ACCENT, fontWeight: '700', fontSize: 12 },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  filterButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: '#e6eaf2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterButtonOn: { backgroundColor: PE_ACCENT, borderColor: PE_ACCENT },
  filterBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: PE_NAVY,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.background,
  },
  filterBadgeText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 10,
    lineHeight: 13,
  },
  applied: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  appliedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 30,
    paddingLeft: 10,
    paddingRight: 8,
    borderRadius: 999,
    backgroundColor: PE_ACCENT_SOFT,
  },
  appliedText: {
    color: PE_ACCENT,
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 16,
  },
  searchField: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    height: 44,
    borderRadius: 14,
    paddingHorizontal: 12,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: '#e6eaf2',
  },
  searchInput: { flex: 1, color: PE_NAVY, fontSize: 13.5, padding: 0 },
  chips: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.s12,
  },
  chip: {
    height: 34,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: '#e6eaf2',
    justifyContent: 'center',
  },
  chipOn: { backgroundColor: PE_ACCENT, borderColor: PE_ACCENT },
  chipText: { color: PE_NAVY, fontWeight: '600', fontSize: 12.5 },
  chipTextOn: { color: '#ffffff' },
  toolRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  cityChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
  },
  cityText: { color: PE_NAVY, fontWeight: '700', fontSize: 13 },
  sortButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: '#e6eaf2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  list: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xl,
    gap: spacing.s12,
  },
  card: {
    backgroundColor: colors.background,
    borderRadius: 18,
    overflow: 'hidden',
    ...shadow,
  },
  cover: { height: 170, backgroundColor: '#e9edf5' },
  coverImage: { width: '100%', height: '100%' },
  coverPill: { position: 'absolute', top: 10, left: 10 },
  coverRight: { position: 'absolute', top: 10, right: 10 },
  body: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.s12,
    paddingBottom: spacing.md,
    gap: 7,
  },
  title: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 15.5,
    lineHeight: 21,
    marginBottom: 2,
  },
  price: {
    color: PE_ACCENT,
    fontWeight: '800',
    fontSize: 14.5,
    lineHeight: 20,
    marginTop: 4,
  },
  soldOut: { color: PE_LIVE, fontWeight: '700', fontSize: 13, marginTop: 2 },
  empty: {
    alignItems: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.s12,
  },
});

/** 3 — the event. */
export const detailUi = StyleSheet.create({
  cover: { height: 280, backgroundColor: '#1b1438' },
  coverImage: { width: '100%', height: '100%' },
  topShade: { position: 'absolute', top: 0, left: 0, right: 0 },
  topButtons: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  coverPills: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: 34,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sheet: {
    marginTop: -22,
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: spacing.md,
    paddingTop: spacing.lg,
    gap: spacing.md,
  },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 22, lineHeight: 29 },
  fact: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.s12 },
  factText: { flex: 1 },
  factValue: {
    color: PE_NAVY,
    fontWeight: '600',
    fontSize: 13.5,
    lineHeight: 19,
  },
  factNote: { color: PE_MUTED, fontSize: 12.5, marginTop: 3, lineHeight: 18 },
  organizer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    paddingVertical: 2,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: PE_ACCENT_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: PE_ACCENT, fontWeight: '800', fontSize: 13 },
  organizerName: {
    color: PE_NAVY,
    fontWeight: '700',
    fontSize: 13.5,
    lineHeight: 19,
  },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  sectionTitle: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 15,
    lineHeight: 21,
  },
  link: { color: PE_ACCENT, fontWeight: '700', fontSize: 13, lineHeight: 18 },
  about: { color: '#4b5568', fontSize: 13.5, lineHeight: 21 },
  ticketCard: {
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#f6c9b8',
    backgroundColor: '#fff8f5',
    padding: spacing.md,
    gap: 6,
  },
  ticketHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  ticketName: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 14.5,
    lineHeight: 20,
    flex: 1,
  },
  ticketPrice: {
    color: PE_ACCENT,
    fontWeight: '800',
    fontSize: 14.5,
    lineHeight: 20,
  },
  ticketNote: { color: PE_MUTED, fontSize: 12.5, lineHeight: 18 },
  feature: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    borderRadius: 14,
    padding: spacing.s12,
    backgroundColor: '#f4f1ff',
  },
  featureLive: { backgroundColor: '#fff1f1' },
  featureOff: { backgroundColor: '#f2f3f6' },
  going: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    borderRadius: 14,
    padding: spacing.s12,
    backgroundColor: PE_GREEN_SOFT,
  },
  goingButton: {
    backgroundColor: PE_GREEN,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  goingButtonText: { color: '#ffffff', fontWeight: '700', fontSize: 12 },
  featureText: { flex: 1 },
  featureTitle: {
    color: PE_NAVY,
    fontWeight: '700',
    fontSize: 13.5,
    lineHeight: 19,
    marginBottom: 2,
  },
});

/** 4 — choosing tickets. */
export const selectUi = StyleSheet.create({
  option: {
    backgroundColor: colors.background,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'transparent',
    padding: spacing.md,
    gap: 6,
    ...shadow,
  },
  optionOn: { borderColor: PE_ACCENT, backgroundColor: '#fff8f5' },
  optionOff: { opacity: 0.6 },
  head: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  name: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 15,
    lineHeight: 21,
    flex: 1,
  },
  price: { color: PE_ACCENT, fontWeight: '800', fontSize: 15 },
  note: { color: PE_MUTED, fontSize: 12.5, lineHeight: 18 },
  foot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  left: {
    color: PE_GREEN,
    fontWeight: '600',
    fontSize: 12.5,
    lineHeight: 18,
    flexShrink: 1,
  },
  stepper: { flexDirection: 'row', alignItems: 'center', gap: spacing.s12 },
  stepBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#e1e5ee',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  stepBtnOn: { backgroundColor: PE_NAVY, borderColor: PE_NAVY },
  count: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 15,
    minWidth: 18,
    textAlign: 'center',
  },
  stateTag: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#f0f2f6',
  },
  stateTagText: { color: PE_MUTED, fontWeight: '700', fontSize: 11 },
  sumRow: { flexDirection: 'row', justifyContent: 'space-between' },
  sumLabel: { color: PE_MUTED, fontSize: 13, lineHeight: 19 },
  sumValue: { color: PE_NAVY, fontWeight: '600', fontSize: 13, lineHeight: 19 },
  totalLabel: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 15,
    lineHeight: 21,
  },
  totalValue: {
    color: PE_ACCENT,
    fontWeight: '800',
    fontSize: 17,
    lineHeight: 23,
  },
});

/** 5 — checkout. */
export const checkoutUi = StyleSheet.create({
  kv: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.s12,
    marginTop: 10,
  },
  key: { color: PE_MUTED, fontSize: 13, lineHeight: 19, flexShrink: 1 },
  value: { color: PE_NAVY, fontWeight: '600', fontSize: 13, lineHeight: 19 },
  customer: { flexDirection: 'row', alignItems: 'center', gap: spacing.s12 },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: PE_ACCENT_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: PE_ACCENT, fontWeight: '800' },
  customerName: {
    color: PE_NAVY,
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 2,
  },
  method: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e6eaf2',
    padding: spacing.s12,
  },
  methodIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#eef2ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  methodText: { flex: 1 },
  methodTitle: {
    color: PE_NAVY,
    fontWeight: '700',
    fontSize: 13.5,
    lineHeight: 19,
    marginBottom: 2,
  },
});

/** 6 — booking success. */
export const successUi = StyleSheet.create({
  content: { padding: spacing.md, paddingBottom: spacing.xl, gap: spacing.md },
  tick: {
    alignSelf: 'center',
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: PE_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 8,
    borderColor: PE_GREEN_SOFT,
    marginTop: spacing.lg,
  },
  heading: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 24,
    textAlign: 'center',
  },
  sub: { color: PE_MUTED, textAlign: 'center', marginTop: -spacing.sm },
  cover: {
    height: 150,
    borderRadius: 12,
    backgroundColor: '#e9edf5',
    marginBottom: spacing.s12,
  },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 16, marginBottom: 4 },
  actions: { gap: spacing.s12 },
});

/** 7 — my tickets. */
export const ticketsUi = StyleSheet.create({
  tabs: {
    flexDirection: 'row',
    marginHorizontal: spacing.md,
    marginBottom: spacing.s12,
    backgroundColor: '#eceff5',
    borderRadius: 12,
    padding: 4,
  },
  tab: {
    flex: 1,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabOn: { backgroundColor: colors.background, ...shadow },
  tabText: { color: PE_MUTED, fontWeight: '600', fontSize: 13 },
  tabTextOn: { color: PE_ACCENT, fontWeight: '800' },
  card: {
    backgroundColor: colors.background,
    borderRadius: 18,
    overflow: 'hidden',
    ...shadow,
  },
  cover: { height: 140, backgroundColor: '#e9edf5' },
  body: { padding: spacing.s12, gap: 5 },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 15 },
  foot: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  typePill: { backgroundColor: PE_ACCENT_SOFT },
  typePillText: { color: PE_ACCENT },
});

/** The colour of each ticket state's pill. */
export const TICKET_STATE_TINT: Record<string, { bg: string; fg: string }> = {
  upcoming: { bg: '#e8efff', fg: '#3b6fd8' },
  checked_in: { bg: PE_GREEN_SOFT, fg: PE_GREEN },
  completed: { bg: '#eef0f4', fg: PE_MUTED },
  cancelled: { bg: '#fdecec', fg: PE_LIVE },
};

/** 8 — the digital ticket. */
export const passUi = StyleSheet.create({
  screen: { flex: 1, backgroundColor: PE_TICKET_TOP },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    height: 52,
  },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  brandText: { color: '#ffffff', fontWeight: '800', fontSize: 18 },
  content: {
    padding: spacing.lg,
    paddingTop: spacing.sm,
    alignItems: 'center',
    gap: spacing.s12,
  },
  title: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 20,
    lineHeight: 26,
    textAlign: 'center',
  },
  line: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  lineText: { color: 'rgba(255,255,255,0.85)', fontSize: 12.5 },
  qrCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: spacing.lg,
    alignItems: 'center',
    gap: spacing.s12,
    marginTop: spacing.sm,
    alignSelf: 'stretch',
  },
  code: { color: PE_NAVY, fontWeight: '800', fontSize: 16, letterSpacing: 1.5 },
  person: { alignSelf: 'stretch', marginTop: spacing.sm },
  personName: { color: '#ffffff', fontWeight: '700', fontSize: 14 },
  personNote: { color: 'rgba(255,255,255,0.7)', fontSize: 12, marginTop: 2 },
  facts: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.25)',
    paddingTop: spacing.s12,
  },
  factKey: { color: 'rgba(255,255,255,0.65)', fontSize: 11 },
  factVal: { color: '#ffffff', fontWeight: '700', fontSize: 13, marginTop: 2 },
  hint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: spacing.md,
  },
  hintText: { color: 'rgba(255,255,255,0.85)', fontSize: 12.5 },
  checked: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(29,158,117,0.18)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  checkedText: { color: '#7be0bd', fontWeight: '700', fontSize: 12.5 },
  eventLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: spacing.md,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  eventLinkText: { color: '#ffffff', fontWeight: '700', fontSize: 12.5 },
});

/** 9 — memories. */
export const memoriesUi = StyleSheet.create({
  tabs: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.s12,
  },
  tab: {
    height: 34,
    paddingHorizontal: 18,
    borderRadius: 999,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: '#e6eaf2',
    justifyContent: 'center',
  },
  tabOn: { backgroundColor: PE_PURPLE, borderColor: PE_PURPLE },
  tabText: { color: PE_NAVY, fontWeight: '600', fontSize: 12.5 },
  tabTextOn: { color: '#ffffff' },
  grid: { paddingHorizontal: spacing.md, paddingBottom: spacing.xl },
  gridRow: { gap: spacing.sm, marginBottom: spacing.sm },
  tile: {
    flex: 1,
    maxWidth: '49%',
    aspectRatio: 1,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#e3e6ee',
  },
  tileImage: { width: '100%', height: '100%' },
  play: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -18,
    marginLeft: -18,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoTile: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PE_TICKET_BOTTOM,
  },
  pending: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    backgroundColor: 'rgba(14,26,51,0.75)',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  pendingText: { color: '#ffffff', fontSize: 10, fontWeight: '700' },
  add: {
    height: 50,
    borderRadius: 14,
    backgroundColor: PE_PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  viewer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
  },
  viewerImage: { width: '100%', height: '80%' },
  viewerClose: { position: 'absolute', right: spacing.md },
});

/** 10 — the live stream. */
export const liveUi = StyleSheet.create({
  player: {
    height: 220,
    backgroundColor: '#000000',
    borderRadius: 18,
    overflow: 'hidden',
  },
  poster: { width: '100%', height: '100%' },
  posterShade: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  livePill: { position: 'absolute', top: 12, left: 12 },
  bigPlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -30,
    marginLeft: -30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 18, lineHeight: 24 },
  access: {
    backgroundColor: '#f4f1ff',
    borderRadius: 16,
    padding: spacing.md,
    gap: spacing.s12,
  },
  accessHead: { flexDirection: 'row', alignItems: 'center', gap: spacing.s12 },
  accessIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accessTitle: { color: PE_NAVY, fontWeight: '800', fontSize: 14 },
  ok: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.background,
    borderRadius: 10,
    padding: spacing.sm,
  },
  okText: { color: PE_GREEN, fontWeight: '600', fontSize: 12.5, flex: 1 },
  watch: {
    height: 48,
    borderRadius: 14,
    backgroundColor: PE_PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
});

/** The list's filter sheet. */
export const filterUi = StyleSheet.create({
  sheet: { maxHeight: '82%' },
  head: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 17, lineHeight: 23 },
  scroll: { flexGrow: 0 },
  label: {
    color: PE_MUTED,
    fontWeight: '700',
    fontSize: 11.5,
    lineHeight: 16,
    letterSpacing: 0.8,
    marginTop: spacing.sm,
    marginBottom: spacing.s12,
  },
  labelGap: { marginTop: spacing.lg },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e1e5ee',
    backgroundColor: colors.background,
  },
  chipOn: { backgroundColor: PE_ACCENT, borderColor: PE_ACCENT },
  chipText: { color: PE_NAVY, fontWeight: '600', fontSize: 13, lineHeight: 18 },
  chipTextOn: { color: '#ffffff' },
  hint: {
    color: PE_MUTED,
    fontSize: 12,
    lineHeight: 17,
    marginTop: spacing.sm,
  },
  citySearch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    height: 40,
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: spacing.s12,
    backgroundColor: '#f3f5f9',
  },
  citySearchInput: { flex: 1, color: PE_NAVY, fontSize: 13.5, padding: 0 },
  actions: { flexDirection: 'row', gap: spacing.s12, marginTop: spacing.lg },
  action: { flex: 1 },
});
