import { Platform, StyleSheet } from 'react-native';
import { colors, spacing } from '../../theme';
import {
  PE_ACCENT,
  PE_ACCENT_SOFT,
  PE_BORDER,
  PE_GREEN,
  PE_GREEN_SOFT,
  PE_LIVE,
  PE_NAVY,
} from './styles';

/*
 * The public-events screens, as designed: a cool off-white page, white cards
 * with a soft shadow, coral for every action and navy for every word.
 */
export const PE_CANVAS = '#f6f7fb';
export const PE_MUTED = '#6b7385';
export const PE_PURPLE = '#6d4df2';
export const PE_TICKET_TOP = '#1b1446';
export const PE_TICKET_BOTTOM = '#3a1d6e';

const shadow = Platform.select({
  ios: {
    shadowColor: PE_NAVY,
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  android: { elevation: 2 },
});

/** Pieces every screen shares. */
export const ui = StyleSheet.create({
  screen: { flex: 1, backgroundColor: PE_CANVAS },
  centre: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  content: { padding: spacing.md, paddingBottom: spacing.xl, gap: spacing.md },
  card: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: spacing.md,
    ...shadow,
  },
  cardTitle: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 19,
    marginBottom: spacing.s12,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  line: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  lineText: { color: PE_MUTED, fontSize: 12.5, lineHeight: 18, flexShrink: 1 },
  muted: { color: PE_MUTED, lineHeight: 18 },
  error: { color: PE_LIVE, textAlign: 'center', marginTop: spacing.sm },
  retry: { paddingHorizontal: 24, marginTop: 16 },
  flex: { flex: 1 },
  fill: { position: 'absolute', top: 0, left: 0 },
  centerText: { textAlign: 'center' },
  gapTop: { marginTop: 8 },
  sectionTitle: { marginTop: 8, marginBottom: 0 },
  spacer26: { width: 26 },
  scrollPad: { paddingBottom: 24 },
  whitePill: { backgroundColor: '#ffffff' },
  soldOutText: { color: '#d93b3b' },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: PE_BORDER,
    marginVertical: spacing.s12,
  },

  pill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  pillText: { fontWeight: '700', fontSize: 11 },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: PE_LIVE,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#ffffff' },
  livePillText: { color: '#ffffff', fontWeight: '800', fontSize: 10.5 },

  primary: {
    height: 50,
    borderRadius: 14,
    backgroundColor: PE_ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  primaryOff: { opacity: 0.5 },
  primaryText: { color: '#ffffff', fontWeight: '800', fontSize: 15 },
  outline: {
    height: 48,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: PE_ACCENT,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  outlineText: { color: PE_ACCENT, fontWeight: '700', fontSize: 14 },

  bar: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.s12,
    backgroundColor: colors.background,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: PE_BORDER,
    gap: spacing.sm,
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(14,26,51,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* The small event summary on selection and checkout. */
  mini: { flexDirection: 'row', gap: spacing.s12, alignItems: 'center' },
  miniThumb: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: '#e9edf5',
  },
  miniText: { flex: 1, gap: 4 },
  miniTitle: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 19,
  },

  /* Option sheet */
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(14,26,51,0.45)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#e3e6ee',
    marginBottom: spacing.md,
  },
  sheetTitle: { color: PE_NAVY, fontWeight: '800', marginBottom: spacing.xs },
  sheetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 48,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: PE_BORDER,
  },
  sheetRowText: { color: PE_NAVY },
  sheetRowTextOn: { color: PE_ACCENT, fontWeight: '700' },
});

/** 1 — the list. */
export const listUi = StyleSheet.create({
  /* ---- Header: the shared AppHeader, then the search row ---- */
  header: { paddingBottom: spacing.xs },
  ticketsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    backgroundColor: PE_ACCENT_SOFT,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  ticketsButtonText: { color: PE_ACCENT, fontWeight: '700', fontSize: 12, lineHeight: 16 },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    marginTop: spacing.xs,
  },
  searchField: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    height: 46,
    borderRadius: 14,
    paddingHorizontal: 12,
    backgroundColor: colors.background,
    ...shadow,
  },
  searchInput: { flex: 1, color: PE_NAVY, fontSize: 13.5, padding: 0 },
  filterButton: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: colors.background,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow,
  },
  filterButtonOn: {},
  /* Inside the corner: the button clips to its rounded edge. */
  filterBadge: {
    position: 'absolute',
    top: 3,
    right: 3,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: PE_NAVY,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: colors.background,
  },
  filterBadgeText: { color: '#ffffff', fontWeight: '800', fontSize: 10, lineHeight: 13 },

  /* ---- Applied filters and categories ---- */
  applied: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.s12,
  },
  appliedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 30,
    paddingLeft: 10,
    paddingRight: 8,
    borderRadius: 999,
    backgroundColor: PE_ACCENT_SOFT,
  },
  appliedText: { color: PE_ACCENT, fontWeight: '700', fontSize: 12, lineHeight: 16 },
  chips: { gap: spacing.sm, paddingHorizontal: spacing.md, paddingVertical: spacing.s12 },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 36,
    paddingHorizontal: 13,
    borderRadius: 999,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: '#e6eaf2',
    overflow: 'hidden',
  },
  chipOn: { borderColor: 'transparent' },
  chipText: { color: PE_NAVY, fontWeight: '600', fontSize: 12.5, lineHeight: 17 },
  chipTextOn: { color: '#ffffff', fontWeight: '700' },

  /* ---- Poster cards ---- */
  list: { paddingHorizontal: spacing.md, paddingBottom: spacing.xl, gap: spacing.md },
  card: {
    backgroundColor: colors.background,
    borderRadius: 22,
    overflow: 'hidden',
    ...shadow,
  },
  poster: { height: 210, backgroundColor: '#1b1438' },
  posterImage: { width: '100%', height: '100%' },
  posterShade: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  categoryPill: {
    position: 'absolute',
    top: 12,
    left: 12,
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 11,
    paddingVertical: 5,
    maxWidth: '60%',
  },
  categoryPillText: { color: '#ffffff', fontWeight: '800', fontSize: 11, lineHeight: 15 },
  dateBlock: {
    position: 'absolute',
    top: 12,
    right: 12,
    minWidth: 50,
    alignItems: 'center',
    borderRadius: 14,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  dateDay: { color: PE_NAVY, fontSize: 20, lineHeight: 23, fontWeight: '800' },
  dateMonth: { color: PE_ACCENT, fontSize: 10.5, lineHeight: 13, fontWeight: '800', letterSpacing: 0.8 },
  livePill: { position: 'absolute', top: 76, right: 12 },
  posterText: { position: 'absolute', left: 14, right: 14, bottom: 12, gap: 4 },
  title: { color: '#ffffff', fontWeight: '800', fontSize: 17, lineHeight: 22 },
  posterLine: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  posterLineText: { color: 'rgba(255,255,255,0.88)', fontSize: 12, lineHeight: 16, flexShrink: 1 },
  strip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  priceBlock: { flexShrink: 1 },
  priceFrom: { color: PE_MUTED, fontSize: 10.5, lineHeight: 14 },
  price: { color: PE_NAVY, fontWeight: '800', fontSize: 17, lineHeight: 22 },
  notePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 1,
    borderRadius: 999,
    backgroundColor: '#f1f3f7',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  notePillSold: { backgroundColor: '#fdecec' },
  noteText: { color: PE_NAVY, fontWeight: '700', fontSize: 12, lineHeight: 16, flexShrink: 1 },
  noteTextSold: { color: '#d93b3b' },
  book: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    overflow: 'hidden',
    paddingLeft: 14,
    paddingRight: 10,
    paddingVertical: 9,
  },
  bookText: { color: '#ffffff', fontWeight: '800', fontSize: 12.5, lineHeight: 16 },
  empty: { alignItems: 'center', paddingVertical: spacing.xl, gap: spacing.s12 },
});

/** 3 — the event. */
export const detailUi = StyleSheet.create({
  cover: { height: 280, backgroundColor: '#1b1438' },
  coverImage: { width: '100%', height: '100%' },
  topShade: { position: 'absolute', top: 0, left: 0, right: 0 },
  topButtons: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  coverPills: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: 34,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sheet: {
    marginTop: -22,
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: spacing.md,
    paddingTop: spacing.lg,
    gap: spacing.md,
  },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 20, lineHeight: 26 },
  fact: { flexDirection: 'row', alignItems: 'center', gap: spacing.s12 },
  factText: { flex: 1 },
  factValue: { color: PE_NAVY, fontWeight: '700', fontSize: 13.5, lineHeight: 19 },
  factNote: { color: PE_MUTED, fontSize: 12, marginTop: 2, lineHeight: 17 },
  organizer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    padding: spacing.s12,
    borderRadius: 16,
    backgroundColor: '#f7f5fb',
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: PE_ACCENT, fontWeight: '800', fontSize: 13 },
  organizerName: { color: PE_NAVY, fontWeight: '700', fontSize: 14, lineHeight: 19 },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  sectionTitle: { color: PE_NAVY, fontWeight: '800', fontSize: 15, lineHeight: 21 },
  link: { color: PE_ACCENT, fontWeight: '700', fontSize: 13, lineHeight: 18 },
  about: { color: '#4b5568', fontSize: 13, lineHeight: 20 },
  ticketCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ece7f6',
    backgroundColor: '#ffffff',
    padding: spacing.md,
    paddingLeft: spacing.md + 6,
    gap: 6,
    overflow: 'hidden',
  },
  ticketHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  ticketName: { color: PE_NAVY, fontWeight: '800', fontSize: 14.5, lineHeight: 20, flex: 1 },
  ticketPrice: { color: '#e2552f', fontWeight: '800', fontSize: 13.5, lineHeight: 18 },
  ticketNote: { color: PE_MUTED, fontSize: 12.5, lineHeight: 18 },
  feature: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    borderRadius: 16,
    padding: spacing.s12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eceff4',
  },
  featureLive: { backgroundColor: '#fff1f1' },
  featureOff: { backgroundColor: '#f7f8fa' },
  going: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    borderRadius: 18,
    padding: spacing.s12,
    overflow: 'hidden',
  },
  goingButton: {
    backgroundColor: '#ffffff',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  goingButtonText: { color: '#0e8a68', fontWeight: '800', fontSize: 12, lineHeight: 16 },
  featureText: { flex: 1 },
  featureTitle: {
    color: PE_NAVY,
    fontWeight: '700',
    fontSize: 13.5,
    lineHeight: 19,
    marginBottom: 2,
  },
  factLabel: { color: PE_MUTED, fontSize: 11, lineHeight: 15, fontWeight: '600' },
  iconTile: {
    width: 40,
    height: 40,
    borderRadius: 13,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarRing: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  organizerText: { flex: 1 },
  organizerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    borderRadius: 999,
    backgroundColor: '#e9f0fd',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  organizerBadgeText: { color: '#2554b8', fontWeight: '700', fontSize: 11, lineHeight: 14 },
  ticketStrip: { position: 'absolute', top: 0, bottom: 0, left: 0, width: 5 },
  ticketPricePill: {
    borderRadius: 999,
    backgroundColor: '#fff0e8',
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  goingIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  goingTitle: { color: '#ffffff', fontWeight: '800', fontSize: 14.5, lineHeight: 20 },
  goingBody: { color: 'rgba(255,255,255,0.88)', fontSize: 12, lineHeight: 16 },
  barRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.s12 },
  barPrice: { flexShrink: 0 },
  barPriceLabel: { color: PE_MUTED, fontSize: 11, lineHeight: 15 },
  barPriceValue: { color: PE_NAVY, fontWeight: '800', fontSize: 18, lineHeight: 23 },
  bookButton: {
    flex: 1,
    height: 50,
    borderRadius: 16,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  bookButtonOff: { opacity: 0.95 },
  bookText: { color: '#ffffff', fontWeight: '800', fontSize: 14.5, lineHeight: 19, flexShrink: 1 },
});

/** 4 — choosing tickets. */
export const selectUi = StyleSheet.create({
  option: {
    backgroundColor: colors.background,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'transparent',
    padding: spacing.md,
    gap: 6,
    ...shadow,
  },
  optionOn: { borderColor: PE_ACCENT, backgroundColor: '#fff8f5' },
  optionOff: { opacity: 0.6 },
  head: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  name: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 15,
    lineHeight: 21,
    flex: 1,
  },
  price: { color: PE_ACCENT, fontWeight: '800', fontSize: 15 },
  note: { color: PE_MUTED, fontSize: 12.5, lineHeight: 18 },
  foot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  left: {
    color: PE_GREEN,
    fontWeight: '600',
    fontSize: 12.5,
    lineHeight: 18,
    flexShrink: 1,
  },
  stepper: { flexDirection: 'row', alignItems: 'center', gap: spacing.s12 },
  stepBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#e1e5ee',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  stepBtnOn: { backgroundColor: PE_NAVY, borderColor: PE_NAVY },
  count: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 15,
    minWidth: 18,
    textAlign: 'center',
  },
  stateTag: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#f0f2f6',
  },
  stateTagText: { color: PE_MUTED, fontWeight: '700', fontSize: 11 },
  sumRow: { flexDirection: 'row', justifyContent: 'space-between' },
  sumLabel: { color: PE_MUTED, fontSize: 13, lineHeight: 19 },
  sumValue: { color: PE_NAVY, fontWeight: '600', fontSize: 13, lineHeight: 19 },
  totalLabel: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 15,
    lineHeight: 21,
  },
  totalValue: {
    color: PE_ACCENT,
    fontWeight: '800',
    fontSize: 17,
    lineHeight: 23,
  },
});

/** 5 — checkout. */
export const checkoutUi = StyleSheet.create({
  kv: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.s12,
    marginTop: 10,
  },
  key: { color: PE_MUTED, fontSize: 13, lineHeight: 19, flexShrink: 1 },
  value: { color: PE_NAVY, fontWeight: '600', fontSize: 13, lineHeight: 19 },
  customer: { flexDirection: 'row', alignItems: 'center', gap: spacing.s12 },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: PE_ACCENT_SOFT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: PE_ACCENT, fontWeight: '800' },
  customerName: {
    color: PE_NAVY,
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 2,
  },
  method: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e6eaf2',
    padding: spacing.s12,
  },
  methodIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#eef2ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  methodText: { flex: 1 },
  methodTitle: {
    color: PE_NAVY,
    fontWeight: '700',
    fontSize: 13.5,
    lineHeight: 19,
    marginBottom: 2,
  },
});

/** 6 — booking success. */
export const successUi = StyleSheet.create({
  content: { padding: spacing.md, paddingBottom: spacing.xl, gap: spacing.md },
  tick: {
    alignSelf: 'center',
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: PE_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 8,
    borderColor: PE_GREEN_SOFT,
    marginTop: spacing.lg,
  },
  heading: {
    color: PE_NAVY,
    fontWeight: '800',
    fontSize: 24,
    textAlign: 'center',
  },
  sub: { color: PE_MUTED, textAlign: 'center', marginTop: -spacing.sm },
  cover: {
    height: 150,
    borderRadius: 12,
    backgroundColor: '#e9edf5',
    marginBottom: spacing.s12,
  },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 16, marginBottom: 4 },
  actions: { gap: spacing.s12 },
});

/** The colour of each ticket state's pill. */
export const TICKET_STATE_TINT: Record<string, { bg: string; fg: string }> = {
  upcoming: { bg: '#e8efff', fg: '#3b6fd8' },
  checked_in: { bg: PE_GREEN_SOFT, fg: PE_GREEN },
  completed: { bg: '#eef0f4', fg: PE_MUTED },
  cancelled: { bg: '#fdecec', fg: PE_LIVE },
};

/** 8 — the digital ticket. */
export const passUi = StyleSheet.create({
  screen: { flex: 1, backgroundColor: PE_TICKET_TOP },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    height: 52,
  },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  brandText: { color: '#ffffff', fontWeight: '800', fontSize: 18 },
  content: {
    padding: spacing.lg,
    paddingTop: spacing.sm,
    alignItems: 'center',
    gap: spacing.s12,
  },
  title: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 20,
    lineHeight: 26,
    textAlign: 'center',
  },
  line: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  lineText: { color: 'rgba(255,255,255,0.85)', fontSize: 12.5 },
  qrCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: spacing.lg,
    alignItems: 'center',
    gap: spacing.s12,
    marginTop: spacing.sm,
    alignSelf: 'stretch',
  },
  code: { color: PE_NAVY, fontWeight: '800', fontSize: 16, letterSpacing: 1.5 },
  person: { alignSelf: 'stretch', marginTop: spacing.sm },
  personName: { color: '#ffffff', fontWeight: '700', fontSize: 14 },
  personNote: { color: 'rgba(255,255,255,0.7)', fontSize: 12, marginTop: 2 },
  facts: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.25)',
    paddingTop: spacing.s12,
  },
  factKey: { color: 'rgba(255,255,255,0.65)', fontSize: 11 },
  factVal: { color: '#ffffff', fontWeight: '700', fontSize: 13, marginTop: 2 },
  hint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: spacing.md,
  },
  hintText: { color: 'rgba(255,255,255,0.85)', fontSize: 12.5 },
  checked: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(29,158,117,0.18)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  checkedText: { color: '#7be0bd', fontWeight: '700', fontSize: 12.5 },
  eventLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: spacing.md,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  eventLinkText: { color: '#ffffff', fontWeight: '700', fontSize: 12.5 },
});

/** 9 — memories. */
export const memoriesUi = StyleSheet.create({
  tabs: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.s12,
  },
  tab: {
    height: 34,
    paddingHorizontal: 18,
    borderRadius: 999,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: '#e6eaf2',
    justifyContent: 'center',
  },
  tabOn: { backgroundColor: PE_PURPLE, borderColor: PE_PURPLE },
  tabText: { color: PE_NAVY, fontWeight: '600', fontSize: 12.5 },
  tabTextOn: { color: '#ffffff' },
  grid: { paddingHorizontal: spacing.md, paddingBottom: spacing.xl },
  gridRow: { gap: spacing.sm, marginBottom: spacing.sm },
  tile: {
    flex: 1,
    maxWidth: '49%',
    aspectRatio: 1,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#e3e6ee',
  },
  tileImage: { width: '100%', height: '100%' },
  play: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -18,
    marginLeft: -18,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoTile: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PE_TICKET_BOTTOM,
  },
  pending: {
    position: 'absolute',
    left: 6,
    bottom: 6,
    backgroundColor: 'rgba(14,26,51,0.75)',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  pendingText: { color: '#ffffff', fontSize: 10, fontWeight: '700' },
  add: {
    height: 50,
    borderRadius: 14,
    backgroundColor: PE_PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  viewer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
  },
  viewerImage: { width: '100%', height: '80%' },
  viewerClose: { position: 'absolute', right: spacing.md },
});

/** 10 — the live stream. */
export const liveUi = StyleSheet.create({
  player: {
    height: 220,
    backgroundColor: '#000000',
    borderRadius: 18,
    overflow: 'hidden',
  },
  poster: { width: '100%', height: '100%' },
  posterShade: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  livePill: { position: 'absolute', top: 12, left: 12 },
  bigPlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -30,
    marginLeft: -30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255,255,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 18, lineHeight: 24 },
  access: {
    backgroundColor: '#f4f1ff',
    borderRadius: 16,
    padding: spacing.md,
    gap: spacing.s12,
  },
  accessHead: { flexDirection: 'row', alignItems: 'center', gap: spacing.s12 },
  accessIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accessTitle: { color: PE_NAVY, fontWeight: '800', fontSize: 14 },
  ok: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.background,
    borderRadius: 10,
    padding: spacing.sm,
  },
  okText: { color: PE_GREEN, fontWeight: '600', fontSize: 12.5, flex: 1 },
  watch: {
    height: 48,
    borderRadius: 14,
    backgroundColor: PE_PURPLE,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
});

/** The list's filter sheet. */
export const filterUi = StyleSheet.create({
  sheet: { maxHeight: '82%' },
  head: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 17, lineHeight: 23 },
  scroll: { flexGrow: 0 },
  label: {
    color: PE_MUTED,
    fontWeight: '700',
    fontSize: 11.5,
    lineHeight: 16,
    letterSpacing: 0.8,
    marginTop: spacing.sm,
    marginBottom: spacing.s12,
  },
  labelGap: { marginTop: spacing.lg },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e1e5ee',
    backgroundColor: colors.background,
  },
  chipOn: { backgroundColor: PE_ACCENT, borderColor: PE_ACCENT },
  chipText: { color: PE_NAVY, fontWeight: '600', fontSize: 13, lineHeight: 18 },
  chipTextOn: { color: '#ffffff' },
  hint: {
    color: PE_MUTED,
    fontSize: 12,
    lineHeight: 17,
    marginTop: spacing.sm,
  },
  citySearch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    height: 40,
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: spacing.s12,
    backgroundColor: '#f3f5f9',
  },
  citySearchInput: { flex: 1, color: PE_NAVY, fontSize: 13.5, padding: 0 },
  actions: { flexDirection: 'row', gap: spacing.s12, marginTop: spacing.lg },
  action: { flex: 1 },
});

/* ---------------------------------------------------------------------------
 * Events near you — the teaser on Home.
 *
 * Two to a row rather than the full-width rows the Discover tab uses: this is
 * a glance on the way past, not a screen somebody came to read, and four
 * events in two rows cost Home half of what four stacked ones would.
 * ------------------------------------------------------------------------- */
/** The Home "Events near you" row: a wide card, and the gap after it. */
export const HOME_EVENT_CARD_WIDTH = 260;
export const HOME_EVENT_GAP = 12;

export const homeUi = StyleSheet.create({
  chipRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    marginTop: 10,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 4,
    height: 36,
    paddingHorizontal: 9,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#e6eaf2',
    backgroundColor: colors.background,
  },
  chipOn: { borderColor: PE_ACCENT, backgroundColor: PE_ACCENT_SOFT },
  chipText: {
    flex: 1,
    minWidth: 0,
    color: PE_NAVY,
    fontSize: 11,
    fontWeight: '700',
  },
  chipTextOn: { color: PE_ACCENT },

  /* The swipeable row. Vertical padding leaves room for the cards' shadow,
     which a horizontal ScrollView would otherwise clip. */
  row: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.s12,
    paddingBottom: spacing.sm,
    gap: HOME_EVENT_GAP,
  },
  card: {
    width: HOME_EVENT_CARD_WIDTH,
    borderRadius: 18,
    backgroundColor: colors.background,
    overflow: 'hidden',
    ...shadow,
  },
  cover: { width: '100%', aspectRatio: 16 / 10, backgroundColor: '#eef0f6' },
  coverTop: {
    position: 'absolute',
    top: 8,
    left: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 6,
  },
  dateChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.95)',
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  dateChipText: { color: PE_NAVY, fontSize: 11, lineHeight: 14, fontWeight: '800' },

  /* Fills whatever height the row settled on, which is what gives the price
     row below something to be pushed to the bottom of. */
  body: { flex: 1, padding: spacing.s12, gap: 4 },
  title: { color: PE_NAVY, fontSize: 13.5, lineHeight: 18, fontWeight: '800' },
  kind: { color: PE_MUTED, fontSize: 12, lineHeight: 17, flexShrink: 1 },
  /*
   * On the floor of the card, not under the last line of text.
   *
   * `auto` eats the slack: a one-line title leaves more of it and the price
   * still lands level with the card beside it. Pinned to the content instead,
   * the two prices in a row sat at different heights and the pair read as
   * misaligned.
   */
  foot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
    marginTop: 'auto',
    paddingTop: 8,
  },
  /* A date or venue line: a small tinted disc with the icon, then the text. */
  metaLine: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  metaIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pricePill: {
    flexShrink: 1,
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  priceFrom: { color: PE_MUTED, fontSize: 11, lineHeight: 16, fontWeight: '600' },
  priceAmount: { fontSize: 13, lineHeight: 17, fontWeight: '800' },
  view: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    borderRadius: 999,
    overflow: 'hidden',
    paddingLeft: 10,
    paddingRight: 6,
    paddingVertical: 5,
    flexShrink: 0,
  },
  viewText: { color: '#ffffff', fontSize: 10.5, lineHeight: 14, fontWeight: '700' },

  note: {
    color: PE_MUTED,
    fontSize: 12.5,
    lineHeight: 18,
    paddingHorizontal: spacing.md,
    marginTop: 10,
  },
});

/** 7 — My Tickets, drawn as tickets: a stub torn along a perforation. */
const MT_CANVAS = '#f6f7fb';
const NOTCH = 22;

export const myTicketsUi = StyleSheet.create({
  screen: { flex: 1, backgroundColor: MT_CANVAS },

  header: { paddingBottom: spacing.sm },
  tabs: {
    flexDirection: 'row',
    marginTop: spacing.sm,
    marginHorizontal: spacing.md,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 4,
    gap: 4,
    ...shadow,
  },
  tab: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  tabText: { color: PE_MUTED, fontWeight: '700', fontSize: 13, lineHeight: 17 },
  tabTextOn: { color: '#ffffff' },
  tabCount: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    paddingHorizontal: 5,
    backgroundColor: '#eef0f5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabCountOn: { backgroundColor: 'rgba(255,255,255,0.28)' },
  tabCountText: { color: PE_MUTED, fontWeight: '800', fontSize: 10.5, lineHeight: 13 },
  tabCountTextOn: { color: '#ffffff' },

  list: { padding: spacing.md, gap: spacing.md },
  card: { backgroundColor: '#ffffff', borderRadius: 20, overflow: 'hidden', ...shadow },
  cardFaded: { opacity: 0.72 },
  cover: { height: 132, backgroundColor: '#1b1438' },
  coverImage: { width: '100%', height: '100%' },
  coverShade: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
  countdown: {
    position: 'absolute',
    left: 12,
    bottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(11,15,36,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  countdownText: { color: '#ffffff', fontWeight: '800', fontSize: 11, lineHeight: 14 },
  body: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 10, gap: 6 },
  title: { color: PE_NAVY, fontWeight: '800', fontSize: 15, lineHeight: 20 },
  line: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  lineIcon: { width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  lineIconDate: { backgroundColor: '#fff0e8' },
  lineIconPlace: { backgroundColor: '#f1ecff' },
  lineText: { color: PE_MUTED, fontSize: 12, lineHeight: 17, flexShrink: 1 },

  /* The perforation: half-circles cut from each edge in the page's colour,
     and a dashed line between them. */
  tear: { height: NOTCH, flexDirection: 'row', alignItems: 'center' },
  notch: { width: NOTCH, height: NOTCH, borderRadius: NOTCH / 2, backgroundColor: MT_CANVAS },
  notchLeft: { marginLeft: -NOTCH / 2 },
  notchRight: { marginRight: -NOTCH / 2 },
  dashes: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
    overflow: 'hidden',
  },
  dash: { width: 6, height: 1.5, borderRadius: 1, backgroundColor: '#dfe3ea' },

  stub: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 14,
  },
  stubLeft: { flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 1, flexWrap: 'wrap' },
  typePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  typeText: { color: '#ffffff', fontWeight: '800', fontSize: 11, lineHeight: 14 },
  statePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  stateDot: { width: 6, height: 6, borderRadius: 3 },
  stateText: { fontWeight: '700', fontSize: 11, lineHeight: 14 },
  qr: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 12,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  qrText: { color: '#ffffff', fontWeight: '800', fontSize: 12, lineHeight: 16 },

  empty: { alignItems: 'center', paddingTop: spacing.xl * 1.5, paddingHorizontal: spacing.lg, gap: spacing.sm },
  emptyIcon: {
    width: 68,
    height: 68,
    borderRadius: 22,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xs,
  },
  emptyTitle: { color: PE_NAVY, fontWeight: '800', fontSize: 16, lineHeight: 22 },
  emptyBody: { color: PE_MUTED, fontSize: 12.5, lineHeight: 18, textAlign: 'center' },
  emptyCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginTop: spacing.sm,
  },
  emptyCtaText: { color: '#ffffff', fontWeight: '800', fontSize: 13, lineHeight: 17 },
});

/* The featured banner at the top of Home's events (sections/FeaturedEvents). */
export const FEATURED_HEIGHT = 178;
export const featuredUi = StyleSheet.create({
  row: { paddingHorizontal: spacing.md, gap: spacing.s12 },
  card: {
    height: FEATURED_HEIGHT,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#1b1446',
  },
  cover: { ...StyleSheet.absoluteFill, width: '100%', height: '100%' },
  body: {
    flex: 1,
    padding: spacing.md,
    justifyContent: 'space-between',
  },
  eyebrow: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 10.5,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 1.4,
  },
  title: {
    color: '#ffffff',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '800',
    marginTop: 2,
    maxWidth: '72%',
  },
  tagline: { color: 'rgba(255,255,255,0.92)', fontSize: 12.5, lineHeight: 17, marginTop: 4 },
  place: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 6, maxWidth: '75%' },
  placeText: { color: 'rgba(255,255,255,0.88)', fontSize: 12, lineHeight: 16, flexShrink: 1 },
  explore: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingVertical: 7,
    paddingLeft: 16,
    paddingRight: 10,
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  exploreText: { color: '#3a2a8c', fontSize: 13, lineHeight: 17, fontWeight: '700' },
  datePill: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  dateText: { color: PE_NAVY, fontSize: 12, lineHeight: 16, fontWeight: '600' },
  dots: {
    position: 'absolute',
    right: spacing.md,
    bottom: spacing.md,
    flexDirection: 'row',
    gap: 5,
  },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.5)' },
  dotActive: { backgroundColor: '#ffffff' },
});

/* The "Live Stream" row on Home (sections/LiveStreams). */
export const LIVE_CARD_WIDTH = 158;
export const LIVE_CARD_HEIGHT = 218;
export const liveRowUi = StyleSheet.create({
  row: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.s12,
    paddingBottom: spacing.sm,
    gap: spacing.s12,
  },
  card: {
    width: LIVE_CARD_WIDTH,
    height: LIVE_CARD_HEIGHT,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#1b1446',
  },
  cover: { ...StyleSheet.absoluteFill, width: '100%', height: '100%' },
  badge: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: PE_LIVE,
  },
  badgeDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#ffffff' },
  badgeText: { color: '#ffffff', fontSize: 10.5, lineHeight: 14, fontWeight: '800', letterSpacing: 0.6 },
  body: { position: 'absolute', left: 12, right: 12, bottom: 12 },
  title: { color: '#ffffff', fontSize: 14, lineHeight: 18, fontWeight: '700' },
  place: { color: 'rgba(255,255,255,0.82)', fontSize: 11.5, lineHeight: 15, marginTop: 3 },
});
